### ISSUE TITLE
A72 /D removes the content of the source file

### ISSUE THREAD

**Issue by mateuszviste** [swanlizard/a72#6]
I noticed in the A72 help screen that A72 supports a few parameters: /A /D and /L. I have no clue what /A and /D are about, so I tried to run them, starting with this:
```
A72 /D file.asm
```
Nothing happened, but when I opened my file.asm again, I was surprised to see its entire content was gone (ie. the file size became 0 bytes). I do not know what the expected result should be, but probably not this.

When I specified an explicit output file with ```A72 /D file.asm file.com``` then the content of the source file wasn't deleted, instead I obtained a huge file.com (20x bigger than it should be).

**Comment by swanlizard** [comment]
The /D option performs a bare-bones disassembly and if no extension is specified on the input file, it will assume .COM as input and .ASM as output.  The /L option performs assembly and generates a listing, by default as a .LST file if no file is specified explicitly.  The /A option is a leftover from testing of a more extended program, it is (currently) an optional switch that directs the program to perform regular assembly.  It's synonymous with running the program, as it is presently, without any input options.  It will only be relevant once it has been expanded with an internal editor and tracer, but those are features that are still a ways off because I keep finding issues in them.  For now consider /A essentially just a dummy switch.
